export const DATA = [{"name":"LOL-palooza","bands":[{"name":"Werewolf Weekday","recordLabel":"XS Recordings"},{"name":"Frank Jupiter","recordLabel":"Pacific Records"},{"name":"Jill Black","recordLabel":"Fourth Woman Records"},{"name":"Winter Primates","recordLabel":""}]},{"name":"Small Night In","bands":[{"name":"Wild Antelope","recordLabel":"Marner Sis. Recording"},{"name":"Squint-281","recordLabel":"Outerscope"},{"name":"The Black Dashes","recordLabel":"Fourth Woman Records"},{"name":"Green Mild Cold Capsicum","recordLabel":"Marner Sis. Recording"},{"name":"Yanke East","recordLabel":"MEDIOCRE Music"}]},{"name":"Trainerella","bands":[{"name":"Wild Antelope","recordLabel":"Still Bottom Records"},{"name":"Manish Ditch","recordLabel":"ACR"},{"name":"Adrian Venti","recordLabel":"Monocracy Records"},{"name":"YOUKRANE","recordLabel":"Anti Records"}]},{"name":"Twisted Tour","bands":[{"name":"Summon","recordLabel":"Outerscope"},{"name":"Squint-281"},{"name":"Auditones","recordLabel":"Marner Sis. Recording"}]},{"bands":[{"name":"Propeller","recordLabel":"Pacific Records"},{"name":"Critter Girls","recordLabel":"ACR"}]}]
// const DATA =[{"name":"LOL-palooza","bands":[{"recordLabel":"XS Recordings"},{"name":"Frank Jupiter","recordLabel":"Pacific Records"},{"name":"Jill Black","recordLabel":"Fourth Woman Records"},{"name":"Winter Primates","recordLabel":""}]},{"name":"Small Night In","bands":[{"name":"Werewolf Weekday","recordLabel":"XS Recordings"},{"name":"Wild Antelope","recordLabel":"Marner Sis. Recording"},{"name":"Squint-281","recordLabel":"Outerscope"},{"name":"The Black Dashes","recordLabel":"Fourth Woman Records"},{"name":"Green Mild Cold Capsicum","recordLabel":"Marner Sis. Recording"},{"name":"Yanke East","recordLabel":"MEDIOCRE Music"}]},{"name":"Trainerella","bands":[{"name":"Wild Antelope","recordLabel":"Still Bottom Records"},{"name":"Manish Ditch","recordLabel":"ACR"},{"name":"Adrian Venti","recordLabel":"Monocracy Records"},{"name":"YOUKRANE","recordLabel":"Anti Records"}]},{"name":"Twisted Tour","bands":[{"name":"Summon","recordLabel":"Outerscope"},{"name":"Squint-281"},{"name":"Auditones","recordLabel":"Marner Sis. Recording"}]},{"bands":[{"name":"Propeller","recordLabel":"Pacific Records"},{"name":"Critter Girls","recordLabel":"ACR"},{"name":"Werewolf Weekday","recordLabel":"XS Recordings"},]}]
// const DATA=[{"name":"LOL-palooza","bands":[{"name":"Werewolf Weekday","recordLabel":"XS Recordings"},{"name":"Frank Jupiter","recordLabel":"Pacific Records"},{"name":"Jill Black","recordLabel":"Fourth Woman Records"},{"name":"Winter Primates","recordLabel":""}]},{"name":"Small Night In","bands":[{"name":"Werewolf Weekday","recordLabel":"XS Recordings"},{"name":"Wild Antelope","recordLabel":"Marner Sis. Recording"},{"name":"Squint-281","recordLabel":"Outerscope"},{"name":"The Black Dashes","recordLabel":"Fourth Woman Records"},{"name":"Green Mild Cold Capsicum","recordLabel":"Marner Sis. Recording"},{"name":"Yanke East","recordLabel":"MEDIOCRE Music"}]},{"name":"Trainerella","bands":[{"name":"Wild Antelope","recordLabel":"Still Bottom Records"},{"name":"Manish Ditch","recordLabel":"ACR"},{"name":"Adrian Venti","recordLabel":"Monocracy Records"},{"name":"YOUKRANE","recordLabel":"Anti Records"}]},{"name":"Twisted Tour","bands":[{"name":"Summon","recordLabel":"Outerscope"},{"name":"Squint-281"},{"name":"Auditones","recordLabel":"Marner Sis. Recording"}]},{"bands":[{"name":"Propeller","recordLabel":"Pacific Records"},{"name":"Critter Girls","recordLabel":"ACR"},{"name":"Werewolf Weekday","recordLabel":"XS Recordings"},]}]
// const DATA=[{"name":"LOL-palooza","bands":[{"name":"Werewolf Weekday","recordLabel":"XS Recordings"},{"name":"Frank Jupiter","recordLabel":"Pacific Records"},{"name":"Jill Black","recordLabel":"Fourth Woman Records"},{"name":"Winter Primates","recordLabel":""}]},{"name":"Small Night In","bands":[{"name":"Werewolf Weekday","recordLabel":"XS Recordings"},{"name":"Wild Antelope","recordLabel":"Marner Sis. Recording"},{"name":"Squint-281","recordLabel":"Outerscope"},{"name":"The Black Dashes","recordLabel":"Fourth Woman Records"},{"name":"Green Mild Cold Capsicum","recordLabel":"Marner Sis. Recording"},{"name":"Yanke East","recordLabel":"MEDIOCRE Music"}]},{"name":"Trainerella","bands":[{"name":"Wild Antelope","recordLabel":"Still Bottom Records"},{"name":"Manish Ditch","recordLabel":"ACR"},{"name":"Adrian Venti","recordLabel":"Monocracy Records"},{"name":"YOUKRANE","recordLabel":"Anti Records"}]},{"name":"Twisted Tour","bands":[{"recordLabel":"Outerscope"},{"name":"Squint-281"},{"name":"Auditones","recordLabel":"Marner Sis. Recording"}]},{"bands":[{"name":"Propeller","recordLabel":"Pacific Records"},{"name":"Critter Girls","recordLabel":"ACR"},{"name":"Werewolf Weekday","recordLabel":"XS Recordings"},]}]
// const DATA=[{"name":"LOL-palooza","bands":[{"name":"Werewolf Weekday","recordLabel":"XS Recordings"},{"name":"Frank Jupiter","recordLabel":"Pacific Records"},{"name":"Jill Black","recordLabel":"Fourth Woman Records"},{"name":"Winter Primates","recordLabel":""}]},{"name":"Small Night In","bands":[{"name":"Werewolf Weekday","recordLabel":"XS Recordings"},{"name":"Wild Antelope","recordLabel":"Marner Sis. Recording"},{"name":"Squint-281","recordLabel":"Outerscope"},{"name":"The Black Dashes","recordLabel":"Fourth Woman Records"},{"name":"Green Mild Cold Capsicum","recordLabel":"Marner Sis. Recording"},{"name":"Yanke East","recordLabel":"MEDIOCRE Music"}]},{"name":"Trainerella","bands":[{"recordLabel":"Still Bottom Records"},{"name":"Manish Ditch","recordLabel":"ACR"},{"name":"Adrian Venti","recordLabel":"Monocracy Records"},{"name":"YOUKRANE","recordLabel":"Anti Records"}]},{"name":"Twisted Tour","bands":[{"recordLabel":"Outerscope"},{"name":"Squint-281"},{"name":"Auditones","recordLabel":"Marner Sis. Recording"}]},{"bands":[{"name":"Propeller","recordLabel":"Pacific Records"},{"name":"Critter Girls","recordLabel":"ACR"},{"name":"Werewolf Weekday","recordLabel":"XS Recordings"},]}]
// const DATA=[{"name":"LOL-palooza","bands":[{"name":"Werewolf Weekday","recordLabel":"XS Recordings"},{"name":"Frank Jupiter","recordLabel":"Pacific Records"},{"name":"Jill Black","recordLabel":"Fourth Woman Records"},{"name":"Winter Primates","recordLabel":""}]},{"name":"Small Night In","bands":[{"name":"Werewolf Weekday","recordLabel":"XS Recordings"},{"name":"Werewolf Weekday","recordLabel":"XS Recordings"},{"name":"Wild Antelope","recordLabel":"Marner Sis. Recording"},{"name":"Squint-281","recordLabel":"Outerscope"},{"name":"The Black Dashes","recordLabel":"Fourth Woman Records"},{"name":"Green Mild Cold Capsicum","recordLabel":"Marner Sis. Recording"},{"name":"Yanke East","recordLabel":"MEDIOCRE Music"}]},{"name":"Trainerella","bands":[{"recordLabel":"Still Bottom Records"},{"name":"Manish Ditch","recordLabel":"ACR"},{"name":"Adrian Venti","recordLabel":"Monocracy Records"},{"name":"YOUKRANE","recordLabel":"Anti Records"}]},{"name":"Twisted Tour","bands":[{"recordLabel":"Outerscope"},{"name":"Squint-281"},{"name":"Auditones","recordLabel":"Marner Sis. Recording"}]},{"bands":[{"name":"Propeller","recordLabel":"Pacific Records"},{"name":"Critter Girls","recordLabel":"ACR"},{"name":"Werewolf Weekday","recordLabel":"XS Recordings"},]}]
// const DATA= [
//   {
//     "name": "LOL-palooza",
//     "bands": [
//       {
//         "name": "Werewolf Weekday",
//         "recordLabel": "XS Recordings"
//       },
//       {
//         "name": "Frank Jupiter",
//         "recordLabel": "Pacific Records"
//       },
//       {
//         "name": "Jill Black",
//         "recordLabel": "Fourth Woman Records"
//       },
//       {
//         "name": "Winter Primates",
//         "recordLabel": ""
//       }
//     ]
//   }]
// const DATA= []